name = "qard-ai-proxy"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "RL"
id = "853520a862d2490fb95c0d6121b62053"

[vars]
MAX_BODY_BYTES = "16384"
MAX_TOKENS = "8000"
